# -*- coding: utf-8 -*-
"""mineru_pdf_to_markdown_json_tutorial_Marktechpost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Rf2vbNQOVmYXC97ep-EXU70UtJCtsYa
"""

import os, sys, subprocess, glob, json, shutil, urllib.request

def run(cmd, check=True):
    if isinstance(cmd, str):
        cmd = cmd.split()
    print(f"\n$ {' '.join(cmd)}\n")
    code = subprocess.run(cmd).returncode
    if check and code != 0:
        raise RuntimeError(f"Command failed ({code}): {' '.join(cmd)}")
    return code

def install_mineru():
    run([sys.executable, "-m", "pip", "install", "-q", "-U", "pip"])
    run([sys.executable, "-m", "pip", "install", "-q", "-U", "mineru[core]"])
    print("mineru CLI found at:", shutil.which("mineru") or "NOT FOUND")

def show_device():
    try:
        import torch
        if torch.cuda.is_available():
            print("✅ GPU:", torch.cuda.get_device_name(0))
        else:
            print("ℹ️  No GPU — running on CPU (works, just slower).")
            print("   Enable: Runtime → Change runtime type → T4 GPU")
    except Exception as e:
        print("torch not importable yet:", e)

def get_sample_pdf(dest="/content/sample.pdf"):
    sources = [
        "https://raw.githubusercontent.com/opendatalab/MinerU/master/demo/pdfs/demo1.pdf",
        "https://arxiv.org/pdf/2409.18839",
    ]
    for url in sources:
        try:
            print("Downloading sample PDF:", url)
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=60) as r, open(dest, "wb") as f:
                shutil.copyfileobj(r, f)
            if os.path.getsize(dest) > 1000:
                print(f"Saved → {dest} ({os.path.getsize(dest)//1024} KB)")
                return dest
        except Exception as e:
            print("  ...failed:", e)
    print("Falling back to a generated PDF...")
    run([sys.executable, "-m", "pip", "install", "-q", "reportlab"])
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    c = canvas.Canvas(dest, pagesize=letter)
    c.setFont("Helvetica-Bold", 18); c.drawString(72, 720, "MinerU Demo Document")
    c.setFont("Helvetica", 12)
    for i, line in enumerate([
        "This is a sample PDF for the MinerU tutorial.",
        "MinerU converts PDFs into clean Markdown and JSON.",
        "Equation example: E = m * c^2",
        "It also detects tables, figures, and reading order.",
    ]):
        c.drawString(72, 690 - i*22, line)
    c.save(); print(f"Saved → {dest}")
    return dest

def parse_pdf(input_path, out_dir="/content/mineru_out", backend="pipeline", lang=None):
    os.makedirs(out_dir, exist_ok=True)
    cmd = ["mineru", "-p", input_path, "-o", out_dir, "-b", backend]
    if lang:
        cmd += ["-l", lang]
    print("⏳ First run downloads the models (a few minutes); later runs are fast.")
    run(cmd)
    return out_dir

def show_results(out_dir, max_md_chars=4000, max_images=4):
    md_files = glob.glob(os.path.join(out_dir, "**", "*.md"), recursive=True)
    if not md_files:
        print("No .md found. Full tree:")
        for root, _, fs in os.walk(out_dir):
            for fn in fs: print(" ", os.path.join(root, fn))
        return
    md_path = md_files[0]
    base = os.path.dirname(md_path)
    print("=" * 70, "\nOUTPUT FOLDER:", base)
    for root, _, fs in os.walk(base):
        for fn in sorted(fs):
            p = os.path.join(root, fn)
            print(f"  {os.path.relpath(p, base):45s} {os.path.getsize(p)//1024:>6} KB")
    print("=" * 70)

    md = open(md_path, encoding="utf-8").read()
    print(f"\n--- {os.path.basename(md_path)} (first {max_md_chars} chars) ---\n")
    print(md[:max_md_chars] + ("\n... [truncated] ..." if len(md) > max_md_chars else ""))

    cl = glob.glob(os.path.join(base, "*content_list*.json"))
    if cl:
        data = json.load(open(cl[0], encoding="utf-8"))
        print(f"\n--- {os.path.basename(cl[0])}: {len(data)} blocks; first 3 ---")
        print(json.dumps(data[:3], ensure_ascii=False, indent=2)[:1500])

    try:
        from IPython.display import display, Markdown, Image
        print("\n================  RENDERED MARKDOWN  ================\n")
        display(Markdown(md[:max_md_chars]))
        for img in glob.glob(os.path.join(base, "images", "*"))[:max_images]:
            print("Image:", os.path.basename(img)); display(Image(filename=img))
    except Exception as e:
        print("(rich display only works in a notebook):", e)
    return md_path

install_mineru()
show_device()
SAMPLE = get_sample_pdf()
OUT = parse_pdf(SAMPLE, backend="pipeline", lang=None)
show_results(OUT)
print("\n✅ Done. Change SAMPLE / backend / lang above to parse your own files.")